spring:
    profiles:
        active: ${profile}
    application:
        name: module-admin-api
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC(Noly4WVAQDXKB5NcO7f9ryzyQ0gX4XkWct4t92U7OySH5ji392yhP65cQ0VOQypaq5NoMUpBnm/EHterr1/YlZ0ukpx4zNl1wXeRe7Fld0NJyw60JzmEmHgWc0VZiv2QnOHFOCYR8VM=)
        username: ENC(UTggmUFFsw/1T9WXYPZnVQ==)
        password: ENC(chMnRg6a7qFnk+u045AOvKYv9qey7lwA)