spring:
    application:
        name: module-admin-api
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/potato_mall?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
        username: root
        password: Jhan562!