spring:
    profiles:
        active: ${profile}
    application:
        name: module-user-api
    datasource: # 데이터베이스 설정
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC(Noly4WVAQDXKB5NcO7f9ryzyQ0gX4XkWct4t92U7OySH5ji392yhP65cQ0VOQypaq5NoMUpBnm/EHterr1/YlZ0ukpx4zNl1wXeRe7Fld0NJyw60JzmEmHgWc0VZiv2QnOHFOCYR8VM=)
        username: ENC(UTggmUFFsw/1T9WXYPZnVQ==)
        password: ENC(chMnRg6a7qFnk+u045AOvKYv9qey7lwA)
    mail: # SMTP 설정
        host: smtp.gmail.com
        port: 465
        username: ENC(fTJhbTbmeQ1jR4+N67J18KDocXSPTv2Tn3FJcCgS5YY=)
        password: ENC(Pk3etLS6OjoRxnec9Az9ETtKbupBz4cnN8BgBtHvXm4=)
        protocol: smtps
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 20000
                    connectiontimeout: 20000
                    writetimeout: 20000
springdoc: # Rest API 문서화 설정
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    swagger-ui:
        url: /docs/openapi3.yaml
        path: /docs/swagger
