spring:
    config:
        activate:
            on-profile: prod
    jpa:
        hibernate:
            ddl-auto: none
    data:
        redis:
            port: 6379
            host: algopuni-redis-001.f2xyi1.0001.apn2.cache.amazonaws.com:6379
