name: algopuni-ci/cd
on:
    push:
        branches:
            - main
#        paths:
#            - 'module-user-api/**'
#            - 'module-admin-api/**'
#            - 'module-common/**'
permissions:
    checks: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4
            #
            #            -   name: Set up JDK 17
            #                uses: actions/setup-java@v4
            #                with:
            #                    java-version: '17'
            #                    distribution: 'temurin'
            #                    cache: gradle
            #
            #            -   name: Verify JDK installation
            #                run: java -version
            #
            #            -   name: Set up Gradle
            #                uses: gradle/actions/setup-gradle@v3
            #                with:
            #                    gradle-version: '8.10'

            -   name: Get changed files
                id: changed-files
                uses: tj-actions/changed-files@v45

            -   name: List all changed files
                env:
                    ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
                run: |
                    for file in ${ALL_CHANGED_FILES}; do
                        echo "$file was changed"
                        if [[ $file == *"module-common"* ]]; then
                            echo "true" >> $COMMON_CHANGED
                            break
                        elif [[ $file == *"module-user-api"* ]]; then
                            echo "true" >> $USER_API_CHANGED
                        elif [[ $file == *"module-admin-api"* ]]; then
                            echo "true" >> $ADMIN_API_CHANGED
                        else
                            echo "true" >> $COMMON_CHANGED
                            break
                        fi
                    done
                    
                    echo "common-changed : $COMMON_CHANGED"
                    echo "user-api-changed : $USER_API_CHANGED"
                    echo "admin-api-changed : $ADMIN_API_CHANGED"


            -   name: Fetch Base Branch
                run: git fetch origin +refs/heads/main:refs/remotes/origin/main

            -   name: Get Modified Files
                run: |
                    BASE_SHA=$(git rev-parse origin/main)
                    echo "$BASE_SHA"
                    MODIFIED_FILES=$(git diff --name-only $BASE_SHA ${{ github.sha }} | tr '\n' ' ')
                    echo "$MODIFIED_FILES"
                    echo "MODIFIED_FILES=$MODIFIED_FILES" >> $GITHUB_ENV
                    echo "123"

            -   name: Build And Test
                run: |
                    if [[ $(git diff --name-only HEAD^ HEAD) =~ ^module-common/ ]]; then
                      echo "common change"
                    fi
            #                    echo $(git diff --name-only HEAD^ HEAD)
            #                    if [[ $(git diff --name-only HEAD^ HEAD) =~ "module-user-api" ]]; then
            #                        cd module-user-api
            #                        ./gradlew clean build
            #                    fi
            #                    if [[ $(git diff --name-only HEAD^ HEAD) =~ "module-admin-api" ]]; then
            #                        cd module-admin-api
            #                        ./gradlew clean build
            #                    fi

            -   name: docker image build
                run: |
                    if [[ $(git diff --name-only HEAD^ HEAD) =~ "module-user-api" ]]; then
                        docker build -t potatowoong/algopuni:user-api .
                    fi
                    if [[ $(git diff --name-only HEAD^ HEAD) =~ "module-admin-api" ]]; then
                        docker build -t potatowoong/algopuni:admin-api .
                    fi

            -   name: docker login
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -   name: docker push
                run: |
                    if [[ $(git diff --name-only HEAD^ HEAD) =~ "module-user-api" ]]; then
                        docker push ${{ secrets.DOCKER_USERNAME }}/algopuni:user-api
                    fi
                    if [[ $(git diff --name-only HEAD^ HEAD) =~ "module-admin-api" ]]; then
                        docker push ${{ secrets.DOCKER_USERNAME }}/algopuni:admin-api
                    fi