name: algopuni-ci/cd
on:
    push:
        branches:
            - main
#        paths:
#            - 'module-user-api/**'
#            - 'module-admin-api/**'
#            - 'module-common/**'
permissions:
    checks: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4
            #
            #            -   name: Set up JDK 17
            #                uses: actions/setup-java@v4
            #                with:
            #                    java-version: '17'
            #                    distribution: 'temurin'
            #                    cache: gradle
            #
            #            -   name: Verify JDK installation
            #                run: java -version
            #
            #            -   name: Set up Gradle
            #                uses: gradle/actions/setup-gradle@v3
            #                with:
            #                    gradle-version: '8.10'

            -   name: Get changed files
                id: changed-files
                uses: tj-actions/changed-files@v45

            -   name: List all changed files
                env:
                    ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
                run: |
                    echo "USER_API_CHANGED=false" >> $GITHUB_ENV
                    echo "ADMIN_API_CHANGED=false" >> $GITHUB_ENV
                    
                    for file in ${ALL_CHANGED_FILES}; do
                        echo "$file was changed"
                        if [[ $file == *"module-user-api"* ]]; then
                            echo "USER_API_CHANGED=true" >> $GITHUB_ENV
                            echo "user-api-changed"
                        elif [[ $file == *"module-admin-api"* ]]; then
                            echo "ADMIN_API_CHANGED=true" >> $GITHUB_ENV
                            echo "admin-api-changed"
                        else
                            echo "ADMIN_API_CHANGED=true" >> $GITHUB_ENV
                            echo "USER_API_CHANGED=true" >> $GITHUB_ENV
                            echo "common-changed!!"
                            break
                        fi
                    done

            -   name: Echo changed files
                run: |
                    echo "user-api-changed : $USER_API_CHANGED"
                    echo "admin-api-changed : $ADMIN_API_CHANGED"

            -   name: Build And Test
                run: |
                    if [[ $USER_API_CHANGED == "true" ]]; then
                        ./gradlew :module-user-api:clean :module-user-api:build
                    fi
                    
                    if [[ $ADMIN_API_CHANGED == "true" ]]; then
                        ./gradlew :module-admin-api:clean :module-admin-api:build
                    fi

            -   name: docker image build
                run: |
                    if [[ $USER_API_CHANGED == "true" ]]; then
                        cd module-user-api
                        docker build -t potatowoong/algopuni:user-api .
                        cd ..
                    fi
                    
                    if [[ $ADMIN_API_CHANGED == "true" ]]; then
                        cd module-admin-api
                        docker build -t potatowoong/algopuni:admin-api .
                        cd ..
                    fi

            -   name: docker login
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -   name: docker push
                run: |
                    if [[ $USER_API_CHANGED == "true" ]]; then
                        docker push ${{ secrets.DOCKER_USERNAME }}/algopuni:user-api
                    fi
                    
                    if [[ $ADMIN_API_CHANGED == "true" ]]; then
                        docker push ${{ secrets.DOCKER_USERNAME }}/algopuni:admin-api
                    fi